/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicContatoRouteImport } from './routes/_public/contato'
import { Route as PublicCotacoesRouteImport } from './routes/_public/cotacoes'
import { Route as PublicEventosRouteImport } from './routes/_public/eventos'
import { Route as PublicSobreRouteImport } from './routes/_public/sobre'
import { Route as ConviteTokenRouteImport } from './routes/convite/$token'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminAdministradoresRouteImport } from './routes/_admin/admin/administradores'
import { Route as AdminAdminAgendaRouteImport } from './routes/_admin/admin/agenda'
import { Route as AdminAdminBannersRouteImport } from './routes/_admin/admin/banners'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin/admin/configuracoes'
import { Route as AdminAdminCursosRouteImport } from './routes/_admin/admin/cursos'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminMensagensRouteImport } from './routes/_admin/admin/mensagens'
import { Route as AdminAdminMinhaContaRouteImport } from './routes/_admin/admin/minha-conta'
import { Route as AdminAdminNoticiasRouteImport } from './routes/_admin/admin/noticias'
import { Route as AdminAdminSalasRouteImport } from './routes/_admin/admin/salas'
import { Route as AdminAdminUnimedRouteImport } from './routes/_admin/admin/unimed'
import { Route as AdminAdminUsuariosRouteImport } from './routes/_admin/admin/usuarios'
import { Route as PublicConveniosIndexRouteImport } from './routes/_public/convenios/index'
import { Route as PublicConveniosSlugRouteImport } from './routes/_public/convenios/$slug'
import { Route as PublicCursosIndexRouteImport } from './routes/_public/cursos/index'
import { Route as PublicCursosIdRouteImport } from './routes/_public/cursos/$id'
import { Route as PublicNoticiasIndexRouteImport } from './routes/_public/noticias/index'
import { Route as PublicNoticiasIdRouteImport } from './routes/_public/noticias/$id'
import { Route as AdminAdminAdministradoresIndexRouteImport } from './routes/_admin/admin/administradores/index'
import { Route as AdminAdminAuditoriaIndexRouteImport } from './routes/_admin/admin/auditoria/index'
import { Route as AdminAdminConveniosIndexRouteImport } from './routes/_admin/admin/convenios/index'
import { Route as AdminAdminConveniosIdRouteImport } from './routes/_admin/admin/convenios/$id'
import { Route as AdminAdminConveniosNovoRouteImport } from './routes/_admin/admin/convenios/novo'
import { Route as AdminAdminCotacoesIndexRouteImport } from './routes/_admin/admin/cotacoes/index'
import { Route as AdminAdminCursosIndexRouteImport } from './routes/_admin/admin/cursos/index'
import { Route as AdminAdminEmpresasIdRouteImport } from './routes/_admin/admin/empresas/$id'
import { Route as AdminAdminEmpresasNovoRouteImport } from './routes/_admin/admin/empresas/novo'
import { Route as AdminAdminFinanceiroIndexRouteImport } from './routes/_admin/admin/financeiro/index'
import { Route as AdminAdminGaleriasIndexRouteImport } from './routes/_admin/admin/galerias/index'
import { Route as AdminAdminNoticiasIndexRouteImport } from './routes/_admin/admin/noticias/index'
import { Route as AdminAdminSalasIndexRouteImport } from './routes/_admin/admin/salas/index'
import { Route as AdminAdminUsuariosIndexRouteImport } from './routes/_admin/admin/usuarios/index'
import { Route as AdminAdminUsuariosIdRouteImport } from './routes/_admin/admin/usuarios/$id'
import { Route as AdminAdminUsuariosNovoRouteImport } from './routes/_admin/admin/usuarios/novo'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCotacoesRoute = PublicCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventosRoute = PublicEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAdministradoresRoute =
  AdminAdminAdministradoresRouteImport.update({
    id: '/admin/administradores',
    path: '/admin/administradores',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAgendaRoute = AdminAdminAgendaRouteImport.update({
  id: '/admin/agenda',
  path: '/admin/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBannersRoute = AdminAdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCursosRoute = AdminAdminCursosRouteImport.update({
  id: '/admin/cursos',
  path: '/admin/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMensagensRoute = AdminAdminMensagensRouteImport.update({
  id: '/admin/mensagens',
  path: '/admin/mensagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMinhaContaRoute = AdminAdminMinhaContaRouteImport.update({
  id: '/admin/minha-conta',
  path: '/admin/minha-conta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNoticiasRoute = AdminAdminNoticiasRouteImport.update({
  id: '/admin/noticias',
  path: '/admin/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSalasRoute = AdminAdminSalasRouteImport.update({
  id: '/admin/salas',
  path: '/admin/salas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUnimedRoute = AdminAdminUnimedRouteImport.update({
  id: '/admin/unimed',
  path: '/admin/unimed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsuariosRoute = AdminAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const PublicConveniosIndexRoute = PublicConveniosIndexRouteImport.update({
  id: '/convenios/',
  path: '/convenios/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicConveniosSlugRoute = PublicConveniosSlugRouteImport.update({
  id: '/convenios/$slug',
  path: '/convenios/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCursosIndexRoute = PublicCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCursosIdRoute = PublicCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNoticiasIndexRoute = PublicNoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNoticiasIdRoute = PublicNoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminAdministradoresIndexRoute =
  AdminAdminAdministradoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminAdministradoresRoute,
  } as any)
const AdminAdminAuditoriaIndexRoute =
  AdminAdminAuditoriaIndexRouteImport.update({
    id: '/admin/auditoria/',
    path: '/admin/auditoria/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminConveniosIndexRoute =
  AdminAdminConveniosIndexRouteImport.update({
    id: '/admin/convenios/',
    path: '/admin/convenios/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminConveniosIdRoute = AdminAdminConveniosIdRouteImport.update({
  id: '/admin/convenios/$id',
  path: '/admin/convenios/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminConveniosNovoRoute = AdminAdminConveniosNovoRouteImport.update({
  id: '/admin/convenios/novo',
  path: '/admin/convenios/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCotacoesIndexRoute = AdminAdminCotacoesIndexRouteImport.update({
  id: '/admin/cotacoes/',
  path: '/admin/cotacoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCursosIndexRoute = AdminAdminCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminCursosRoute,
} as any)
const AdminAdminEmpresasIdRoute = AdminAdminEmpresasIdRouteImport.update({
  id: '/admin/empresas/$id',
  path: '/admin/empresas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEmpresasNovoRoute = AdminAdminEmpresasNovoRouteImport.update({
  id: '/admin/empresas/novo',
  path: '/admin/empresas/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFinanceiroIndexRoute =
  AdminAdminFinanceiroIndexRouteImport.update({
    id: '/admin/financeiro/',
    path: '/admin/financeiro/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminGaleriasIndexRoute = AdminAdminGaleriasIndexRouteImport.update({
  id: '/admin/galerias/',
  path: '/admin/galerias/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNoticiasIndexRoute = AdminAdminNoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminNoticiasRoute,
} as any)
const AdminAdminSalasIndexRoute = AdminAdminSalasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminSalasRoute,
} as any)
const AdminAdminUsuariosIndexRoute = AdminAdminUsuariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminUsuariosRoute,
} as any)
const AdminAdminUsuariosIdRoute = AdminAdminUsuariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminUsuariosRoute,
} as any)
const AdminAdminUsuariosNovoRoute = AdminAdminUsuariosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminAdminUsuariosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/contato': typeof PublicContatoRoute
  '/cotacoes': typeof PublicCotacoesRoute
  '/eventos': typeof PublicEventosRoute
  '/sobre': typeof PublicSobreRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/administradores': typeof AdminAdminAdministradoresRouteWithChildren
  '/admin/agenda': typeof AdminAdminAgendaRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/cursos': typeof AdminAdminCursosRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/mensagens': typeof AdminAdminMensagensRoute
  '/admin/minha-conta': typeof AdminAdminMinhaContaRoute
  '/admin/noticias': typeof AdminAdminNoticiasRouteWithChildren
  '/admin/salas': typeof AdminAdminSalasRouteWithChildren
  '/admin/unimed': typeof AdminAdminUnimedRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRouteWithChildren
  '/convenios/$slug': typeof PublicConveniosSlugRoute
  '/cursos/$id': typeof PublicCursosIdRoute
  '/noticias/$id': typeof PublicNoticiasIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/convenios/': typeof PublicConveniosIndexRoute
  '/cursos/': typeof PublicCursosIndexRoute
  '/noticias/': typeof PublicNoticiasIndexRoute
  '/admin/convenios/$id': typeof AdminAdminConveniosIdRoute
  '/admin/convenios/novo': typeof AdminAdminConveniosNovoRoute
  '/admin/empresas/$id': typeof AdminAdminEmpresasIdRoute
  '/admin/empresas/novo': typeof AdminAdminEmpresasNovoRoute
  '/admin/usuarios/$id': typeof AdminAdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminAdminUsuariosNovoRoute
  '/admin/administradores/': typeof AdminAdminAdministradoresIndexRoute
  '/admin/auditoria/': typeof AdminAdminAuditoriaIndexRoute
  '/admin/convenios/': typeof AdminAdminConveniosIndexRoute
  '/admin/cotacoes/': typeof AdminAdminCotacoesIndexRoute
  '/admin/cursos/': typeof AdminAdminCursosIndexRoute
  '/admin/financeiro/': typeof AdminAdminFinanceiroIndexRoute
  '/admin/galerias/': typeof AdminAdminGaleriasIndexRoute
  '/admin/noticias/': typeof AdminAdminNoticiasIndexRoute
  '/admin/salas/': typeof AdminAdminSalasIndexRoute
  '/admin/usuarios/': typeof AdminAdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/contato': typeof PublicContatoRoute
  '/cotacoes': typeof PublicCotacoesRoute
  '/eventos': typeof PublicEventosRoute
  '/sobre': typeof PublicSobreRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/agenda': typeof AdminAdminAgendaRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/mensagens': typeof AdminAdminMensagensRoute
  '/admin/minha-conta': typeof AdminAdminMinhaContaRoute
  '/admin/unimed': typeof AdminAdminUnimedRoute
  '/convenios/$slug': typeof PublicConveniosSlugRoute
  '/cursos/$id': typeof PublicCursosIdRoute
  '/noticias/$id': typeof PublicNoticiasIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/convenios': typeof PublicConveniosIndexRoute
  '/cursos': typeof PublicCursosIndexRoute
  '/noticias': typeof PublicNoticiasIndexRoute
  '/admin/convenios/$id': typeof AdminAdminConveniosIdRoute
  '/admin/convenios/novo': typeof AdminAdminConveniosNovoRoute
  '/admin/empresas/$id': typeof AdminAdminEmpresasIdRoute
  '/admin/empresas/novo': typeof AdminAdminEmpresasNovoRoute
  '/admin/usuarios/$id': typeof AdminAdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminAdminUsuariosNovoRoute
  '/admin/administradores': typeof AdminAdminAdministradoresIndexRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaIndexRoute
  '/admin/convenios': typeof AdminAdminConveniosIndexRoute
  '/admin/cotacoes': typeof AdminAdminCotacoesIndexRoute
  '/admin/cursos': typeof AdminAdminCursosIndexRoute
  '/admin/financeiro': typeof AdminAdminFinanceiroIndexRoute
  '/admin/galerias': typeof AdminAdminGaleriasIndexRoute
  '/admin/noticias': typeof AdminAdminNoticiasIndexRoute
  '/admin/salas': typeof AdminAdminSalasIndexRoute
  '/admin/usuarios': typeof AdminAdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/cotacoes': typeof PublicCotacoesRoute
  '/_public/eventos': typeof PublicEventosRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/administradores': typeof AdminAdminAdministradoresRouteWithChildren
  '/_admin/admin/agenda': typeof AdminAdminAgendaRoute
  '/_admin/admin/banners': typeof AdminAdminBannersRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/cursos': typeof AdminAdminCursosRouteWithChildren
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/mensagens': typeof AdminAdminMensagensRoute
  '/_admin/admin/minha-conta': typeof AdminAdminMinhaContaRoute
  '/_admin/admin/noticias': typeof AdminAdminNoticiasRouteWithChildren
  '/_admin/admin/salas': typeof AdminAdminSalasRouteWithChildren
  '/_admin/admin/unimed': typeof AdminAdminUnimedRoute
  '/_admin/admin/usuarios': typeof AdminAdminUsuariosRouteWithChildren
  '/_public/convenios/$slug': typeof PublicConveniosSlugRoute
  '/_public/cursos/$id': typeof PublicCursosIdRoute
  '/_public/noticias/$id': typeof PublicNoticiasIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/convenios/': typeof PublicConveniosIndexRoute
  '/_public/cursos/': typeof PublicCursosIndexRoute
  '/_public/noticias/': typeof PublicNoticiasIndexRoute
  '/_admin/admin/convenios/$id': typeof AdminAdminConveniosIdRoute
  '/_admin/admin/convenios/novo': typeof AdminAdminConveniosNovoRoute
  '/_admin/admin/empresas/$id': typeof AdminAdminEmpresasIdRoute
  '/_admin/admin/empresas/novo': typeof AdminAdminEmpresasNovoRoute
  '/_admin/admin/usuarios/$id': typeof AdminAdminUsuariosIdRoute
  '/_admin/admin/usuarios/novo': typeof AdminAdminUsuariosNovoRoute
  '/_admin/admin/administradores/': typeof AdminAdminAdministradoresIndexRoute
  '/_admin/admin/auditoria/': typeof AdminAdminAuditoriaIndexRoute
  '/_admin/admin/convenios/': typeof AdminAdminConveniosIndexRoute
  '/_admin/admin/cotacoes/': typeof AdminAdminCotacoesIndexRoute
  '/_admin/admin/cursos/': typeof AdminAdminCursosIndexRoute
  '/_admin/admin/financeiro/': typeof AdminAdminFinanceiroIndexRoute
  '/_admin/admin/galerias/': typeof AdminAdminGaleriasIndexRoute
  '/_admin/admin/noticias/': typeof AdminAdminNoticiasIndexRoute
  '/_admin/admin/salas/': typeof AdminAdminSalasIndexRoute
  '/_admin/admin/usuarios/': typeof AdminAdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contato'
    | '/cotacoes'
    | '/eventos'
    | '/sobre'
    | '/convite/$token'
    | '/admin/administradores'
    | '/admin/agenda'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/cursos'
    | '/admin/dashboard'
    | '/admin/mensagens'
    | '/admin/minha-conta'
    | '/admin/noticias'
    | '/admin/salas'
    | '/admin/unimed'
    | '/admin/usuarios'
    | '/convenios/$slug'
    | '/cursos/$id'
    | '/noticias/$id'
    | '/admin/'
    | '/convenios/'
    | '/cursos/'
    | '/noticias/'
    | '/admin/convenios/$id'
    | '/admin/convenios/novo'
    | '/admin/empresas/$id'
    | '/admin/empresas/novo'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/admin/administradores/'
    | '/admin/auditoria/'
    | '/admin/convenios/'
    | '/admin/cotacoes/'
    | '/admin/cursos/'
    | '/admin/financeiro/'
    | '/admin/galerias/'
    | '/admin/noticias/'
    | '/admin/salas/'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contato'
    | '/cotacoes'
    | '/eventos'
    | '/sobre'
    | '/convite/$token'
    | '/admin/agenda'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/mensagens'
    | '/admin/minha-conta'
    | '/admin/unimed'
    | '/convenios/$slug'
    | '/cursos/$id'
    | '/noticias/$id'
    | '/admin'
    | '/convenios'
    | '/cursos'
    | '/noticias'
    | '/admin/convenios/$id'
    | '/admin/convenios/novo'
    | '/admin/empresas/$id'
    | '/admin/empresas/novo'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/admin/administradores'
    | '/admin/auditoria'
    | '/admin/convenios'
    | '/admin/cotacoes'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/galerias'
    | '/admin/noticias'
    | '/admin/salas'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/login'
    | '/_public/contato'
    | '/_public/cotacoes'
    | '/_public/eventos'
    | '/_public/sobre'
    | '/convite/$token'
    | '/_public/'
    | '/_admin/admin/administradores'
    | '/_admin/admin/agenda'
    | '/_admin/admin/banners'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/cursos'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/mensagens'
    | '/_admin/admin/minha-conta'
    | '/_admin/admin/noticias'
    | '/_admin/admin/salas'
    | '/_admin/admin/unimed'
    | '/_admin/admin/usuarios'
    | '/_public/convenios/$slug'
    | '/_public/cursos/$id'
    | '/_public/noticias/$id'
    | '/_admin/admin/'
    | '/_public/convenios/'
    | '/_public/cursos/'
    | '/_public/noticias/'
    | '/_admin/admin/convenios/$id'
    | '/_admin/admin/convenios/novo'
    | '/_admin/admin/empresas/$id'
    | '/_admin/admin/empresas/novo'
    | '/_admin/admin/usuarios/$id'
    | '/_admin/admin/usuarios/novo'
    | '/_admin/admin/administradores/'
    | '/_admin/admin/auditoria/'
    | '/_admin/admin/convenios/'
    | '/_admin/admin/cotacoes/'
    | '/_admin/admin/cursos/'
    | '/_admin/admin/financeiro/'
    | '/_admin/admin/galerias/'
    | '/_admin/admin/noticias/'
    | '/_admin/admin/salas/'
    | '/_admin/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cotacoes': {
      id: '/_public/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof PublicCotacoesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/eventos': {
      id: '/_public/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof PublicEventosRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/administradores': {
      id: '/_admin/admin/administradores'
      path: '/admin/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdminAdministradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/agenda': {
      id: '/_admin/admin/agenda'
      path: '/admin/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/banners': {
      id: '/_admin/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminAdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cursos': {
      id: '/_admin/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminAdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/mensagens': {
      id: '/_admin/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminAdminMensagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/minha-conta': {
      id: '/_admin/admin/minha-conta'
      path: '/admin/minha-conta'
      fullPath: '/admin/minha-conta'
      preLoaderRoute: typeof AdminAdminMinhaContaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/noticias': {
      id: '/_admin/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminAdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/salas': {
      id: '/_admin/admin/salas'
      path: '/admin/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AdminAdminSalasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/unimed': {
      id: '/_admin/admin/unimed'
      path: '/admin/unimed'
      fullPath: '/admin/unimed'
      preLoaderRoute: typeof AdminAdminUnimedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/usuarios': {
      id: '/_admin/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminAdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/convenios/': {
      id: '/_public/convenios/'
      path: '/convenios'
      fullPath: '/convenios/'
      preLoaderRoute: typeof PublicConveniosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/convenios/$slug': {
      id: '/_public/convenios/$slug'
      path: '/convenios/$slug'
      fullPath: '/convenios/$slug'
      preLoaderRoute: typeof PublicConveniosSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cursos/': {
      id: '/_public/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof PublicCursosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cursos/$id': {
      id: '/_public/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof PublicCursosIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/noticias/': {
      id: '/_public/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof PublicNoticiasIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/noticias/$id': {
      id: '/_public/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof PublicNoticiasIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/administradores/': {
      id: '/_admin/admin/administradores/'
      path: '/'
      fullPath: '/admin/administradores/'
      preLoaderRoute: typeof AdminAdminAdministradoresIndexRouteImport
      parentRoute: typeof AdminAdminAdministradoresRoute
    }
    '/_admin/admin/auditoria/': {
      id: '/_admin/admin/auditoria/'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria/'
      preLoaderRoute: typeof AdminAdminAuditoriaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/convenios/': {
      id: '/_admin/admin/convenios/'
      path: '/admin/convenios'
      fullPath: '/admin/convenios/'
      preLoaderRoute: typeof AdminAdminConveniosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/convenios/$id': {
      id: '/_admin/admin/convenios/$id'
      path: '/admin/convenios/$id'
      fullPath: '/admin/convenios/$id'
      preLoaderRoute: typeof AdminAdminConveniosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/convenios/novo': {
      id: '/_admin/admin/convenios/novo'
      path: '/admin/convenios/novo'
      fullPath: '/admin/convenios/novo'
      preLoaderRoute: typeof AdminAdminConveniosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cotacoes/': {
      id: '/_admin/admin/cotacoes/'
      path: '/admin/cotacoes'
      fullPath: '/admin/cotacoes/'
      preLoaderRoute: typeof AdminAdminCotacoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cursos/': {
      id: '/_admin/admin/cursos/'
      path: '/'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminAdminCursosIndexRouteImport
      parentRoute: typeof AdminAdminCursosRoute
    }
    '/_admin/admin/empresas/$id': {
      id: '/_admin/admin/empresas/$id'
      path: '/admin/empresas/$id'
      fullPath: '/admin/empresas/$id'
      preLoaderRoute: typeof AdminAdminEmpresasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/empresas/novo': {
      id: '/_admin/admin/empresas/novo'
      path: '/admin/empresas/novo'
      fullPath: '/admin/empresas/novo'
      preLoaderRoute: typeof AdminAdminEmpresasNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/financeiro/': {
      id: '/_admin/admin/financeiro/'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro/'
      preLoaderRoute: typeof AdminAdminFinanceiroIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/galerias/': {
      id: '/_admin/admin/galerias/'
      path: '/admin/galerias'
      fullPath: '/admin/galerias/'
      preLoaderRoute: typeof AdminAdminGaleriasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/noticias/': {
      id: '/_admin/admin/noticias/'
      path: '/'
      fullPath: '/admin/noticias/'
      preLoaderRoute: typeof AdminAdminNoticiasIndexRouteImport
      parentRoute: typeof AdminAdminNoticiasRoute
    }
    '/_admin/admin/salas/': {
      id: '/_admin/admin/salas/'
      path: '/'
      fullPath: '/admin/salas/'
      preLoaderRoute: typeof AdminAdminSalasIndexRouteImport
      parentRoute: typeof AdminAdminSalasRoute
    }
    '/_admin/admin/usuarios/': {
      id: '/_admin/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminAdminUsuariosIndexRouteImport
      parentRoute: typeof AdminAdminUsuariosRoute
    }
    '/_admin/admin/usuarios/$id': {
      id: '/_admin/admin/usuarios/$id'
      path: '/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminAdminUsuariosIdRouteImport
      parentRoute: typeof AdminAdminUsuariosRoute
    }
    '/_admin/admin/usuarios/novo': {
      id: '/_admin/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AdminAdminUsuariosNovoRouteImport
      parentRoute: typeof AdminAdminUsuariosRoute
    }
  }
}

interface AdminAdminAdministradoresRouteChildren {
  AdminAdminAdministradoresIndexRoute: typeof AdminAdminAdministradoresIndexRoute
}

const AdminAdminAdministradoresRouteChildren: AdminAdminAdministradoresRouteChildren =
  {
    AdminAdminAdministradoresIndexRoute: AdminAdminAdministradoresIndexRoute,
  }

const AdminAdminAdministradoresRouteWithChildren =
  AdminAdminAdministradoresRoute._addFileChildren(
    AdminAdminAdministradoresRouteChildren,
  )

interface AdminAdminCursosRouteChildren {
  AdminAdminCursosIndexRoute: typeof AdminAdminCursosIndexRoute
}

const AdminAdminCursosRouteChildren: AdminAdminCursosRouteChildren = {
  AdminAdminCursosIndexRoute: AdminAdminCursosIndexRoute,
}

const AdminAdminCursosRouteWithChildren =
  AdminAdminCursosRoute._addFileChildren(AdminAdminCursosRouteChildren)

interface AdminAdminNoticiasRouteChildren {
  AdminAdminNoticiasIndexRoute: typeof AdminAdminNoticiasIndexRoute
}

const AdminAdminNoticiasRouteChildren: AdminAdminNoticiasRouteChildren = {
  AdminAdminNoticiasIndexRoute: AdminAdminNoticiasIndexRoute,
}

const AdminAdminNoticiasRouteWithChildren =
  AdminAdminNoticiasRoute._addFileChildren(AdminAdminNoticiasRouteChildren)

interface AdminAdminSalasRouteChildren {
  AdminAdminSalasIndexRoute: typeof AdminAdminSalasIndexRoute
}

const AdminAdminSalasRouteChildren: AdminAdminSalasRouteChildren = {
  AdminAdminSalasIndexRoute: AdminAdminSalasIndexRoute,
}

const AdminAdminSalasRouteWithChildren = AdminAdminSalasRoute._addFileChildren(
  AdminAdminSalasRouteChildren,
)

interface AdminAdminUsuariosRouteChildren {
  AdminAdminUsuariosIdRoute: typeof AdminAdminUsuariosIdRoute
  AdminAdminUsuariosNovoRoute: typeof AdminAdminUsuariosNovoRoute
  AdminAdminUsuariosIndexRoute: typeof AdminAdminUsuariosIndexRoute
}

const AdminAdminUsuariosRouteChildren: AdminAdminUsuariosRouteChildren = {
  AdminAdminUsuariosIdRoute: AdminAdminUsuariosIdRoute,
  AdminAdminUsuariosNovoRoute: AdminAdminUsuariosNovoRoute,
  AdminAdminUsuariosIndexRoute: AdminAdminUsuariosIndexRoute,
}

const AdminAdminUsuariosRouteWithChildren =
  AdminAdminUsuariosRoute._addFileChildren(AdminAdminUsuariosRouteChildren)

interface AdminRouteChildren {
  AdminAdminAdministradoresRoute: typeof AdminAdminAdministradoresRouteWithChildren
  AdminAdminAgendaRoute: typeof AdminAdminAgendaRoute
  AdminAdminBannersRoute: typeof AdminAdminBannersRoute
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminCursosRoute: typeof AdminAdminCursosRouteWithChildren
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminMensagensRoute: typeof AdminAdminMensagensRoute
  AdminAdminMinhaContaRoute: typeof AdminAdminMinhaContaRoute
  AdminAdminNoticiasRoute: typeof AdminAdminNoticiasRouteWithChildren
  AdminAdminSalasRoute: typeof AdminAdminSalasRouteWithChildren
  AdminAdminUnimedRoute: typeof AdminAdminUnimedRoute
  AdminAdminUsuariosRoute: typeof AdminAdminUsuariosRouteWithChildren
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminConveniosIdRoute: typeof AdminAdminConveniosIdRoute
  AdminAdminConveniosNovoRoute: typeof AdminAdminConveniosNovoRoute
  AdminAdminEmpresasIdRoute: typeof AdminAdminEmpresasIdRoute
  AdminAdminEmpresasNovoRoute: typeof AdminAdminEmpresasNovoRoute
  AdminAdminAuditoriaIndexRoute: typeof AdminAdminAuditoriaIndexRoute
  AdminAdminConveniosIndexRoute: typeof AdminAdminConveniosIndexRoute
  AdminAdminCotacoesIndexRoute: typeof AdminAdminCotacoesIndexRoute
  AdminAdminFinanceiroIndexRoute: typeof AdminAdminFinanceiroIndexRoute
  AdminAdminGaleriasIndexRoute: typeof AdminAdminGaleriasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAdministradoresRoute: AdminAdminAdministradoresRouteWithChildren,
  AdminAdminAgendaRoute: AdminAdminAgendaRoute,
  AdminAdminBannersRoute: AdminAdminBannersRoute,
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminCursosRoute: AdminAdminCursosRouteWithChildren,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminMensagensRoute: AdminAdminMensagensRoute,
  AdminAdminMinhaContaRoute: AdminAdminMinhaContaRoute,
  AdminAdminNoticiasRoute: AdminAdminNoticiasRouteWithChildren,
  AdminAdminSalasRoute: AdminAdminSalasRouteWithChildren,
  AdminAdminUnimedRoute: AdminAdminUnimedRoute,
  AdminAdminUsuariosRoute: AdminAdminUsuariosRouteWithChildren,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminConveniosIdRoute: AdminAdminConveniosIdRoute,
  AdminAdminConveniosNovoRoute: AdminAdminConveniosNovoRoute,
  AdminAdminEmpresasIdRoute: AdminAdminEmpresasIdRoute,
  AdminAdminEmpresasNovoRoute: AdminAdminEmpresasNovoRoute,
  AdminAdminAuditoriaIndexRoute: AdminAdminAuditoriaIndexRoute,
  AdminAdminConveniosIndexRoute: AdminAdminConveniosIndexRoute,
  AdminAdminCotacoesIndexRoute: AdminAdminCotacoesIndexRoute,
  AdminAdminFinanceiroIndexRoute: AdminAdminFinanceiroIndexRoute,
  AdminAdminGaleriasIndexRoute: AdminAdminGaleriasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicContatoRoute: typeof PublicContatoRoute
  PublicCotacoesRoute: typeof PublicCotacoesRoute
  PublicEventosRoute: typeof PublicEventosRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicConveniosSlugRoute: typeof PublicConveniosSlugRoute
  PublicCursosIdRoute: typeof PublicCursosIdRoute
  PublicNoticiasIdRoute: typeof PublicNoticiasIdRoute
  PublicConveniosIndexRoute: typeof PublicConveniosIndexRoute
  PublicCursosIndexRoute: typeof PublicCursosIndexRoute
  PublicNoticiasIndexRoute: typeof PublicNoticiasIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContatoRoute: PublicContatoRoute,
  PublicCotacoesRoute: PublicCotacoesRoute,
  PublicEventosRoute: PublicEventosRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicConveniosSlugRoute: PublicConveniosSlugRoute,
  PublicCursosIdRoute: PublicCursosIdRoute,
  PublicNoticiasIdRoute: PublicNoticiasIdRoute,
  PublicConveniosIndexRoute: PublicConveniosIndexRoute,
  PublicCursosIndexRoute: PublicCursosIndexRoute,
  PublicNoticiasIndexRoute: PublicNoticiasIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
