/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSobreRouteImport } from './routes/_public/sobre'
import { Route as PublicContatoRouteImport } from './routes/_public/contato'
import { Route as PublicNoticiasIndexRouteImport } from './routes/_public/noticias/index'
import { Route as PublicCursosIndexRouteImport } from './routes/_public/cursos/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as PublicNoticiasIdRouteImport } from './routes/_public/noticias/$id'
import { Route as PublicCursosIdRouteImport } from './routes/_public/cursos/$id'
import { Route as AdminAdminUsuariosRouteImport } from './routes/_admin/admin/usuarios'
import { Route as AdminAdminSalasRouteImport } from './routes/_admin/admin/salas'
import { Route as AdminAdminNoticiasRouteImport } from './routes/_admin/admin/noticias'
import { Route as AdminAdminMensagensRouteImport } from './routes/_admin/admin/mensagens'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminCursosRouteImport } from './routes/_admin/admin/cursos'
import { Route as AdminAdminBannersRouteImport } from './routes/_admin/admin/banners'
import { Route as AdminAdminAdministradoresRouteImport } from './routes/_admin/admin/administradores'
import { Route as AdminAdminUsuariosIndexRouteImport } from './routes/_admin/admin/usuarios/index'
import { Route as AdminAdminSalasIndexRouteImport } from './routes/_admin/admin/salas/index'
import { Route as AdminAdminNoticiasIndexRouteImport } from './routes/_admin/admin/noticias/index'
import { Route as AdminAdminCursosIndexRouteImport } from './routes/_admin/admin/cursos/index'
import { Route as AdminAdminCotacoesIndexRouteImport } from './routes/_admin/admin/cotacoes/index'
import { Route as AdminAdminAuditoriaIndexRouteImport } from './routes/_admin/admin/auditoria/index'
import { Route as AdminAdminAdministradoresIndexRouteImport } from './routes/_admin/admin/administradores/index'
import { Route as AdminAdminUsuariosNovoRouteImport } from './routes/_admin/admin/usuarios/novo'
import { Route as AdminAdminUsuariosIdRouteImport } from './routes/_admin/admin/usuarios/$id'
import { Route as AdminAdminCursosNovoRouteImport } from './routes/_admin/admin/cursos/novo'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSobreRoute = PublicSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNoticiasIndexRoute = PublicNoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCursosIndexRoute = PublicCursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicNoticiasIdRoute = PublicNoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCursosIdRoute = PublicCursosIdRouteImport.update({
  id: '/cursos/$id',
  path: '/cursos/$id',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminUsuariosRoute = AdminAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSalasRoute = AdminAdminSalasRouteImport.update({
  id: '/admin/salas',
  path: '/admin/salas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNoticiasRoute = AdminAdminNoticiasRouteImport.update({
  id: '/admin/noticias',
  path: '/admin/noticias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMensagensRoute = AdminAdminMensagensRouteImport.update({
  id: '/admin/mensagens',
  path: '/admin/mensagens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCursosRoute = AdminAdminCursosRouteImport.update({
  id: '/admin/cursos',
  path: '/admin/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBannersRoute = AdminAdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAdministradoresRoute =
  AdminAdminAdministradoresRouteImport.update({
    id: '/admin/administradores',
    path: '/admin/administradores',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminUsuariosIndexRoute = AdminAdminUsuariosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminUsuariosRoute,
} as any)
const AdminAdminSalasIndexRoute = AdminAdminSalasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminSalasRoute,
} as any)
const AdminAdminNoticiasIndexRoute = AdminAdminNoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminNoticiasRoute,
} as any)
const AdminAdminCursosIndexRoute = AdminAdminCursosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminCursosRoute,
} as any)
const AdminAdminCotacoesIndexRoute = AdminAdminCotacoesIndexRouteImport.update({
  id: '/admin/cotacoes/',
  path: '/admin/cotacoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAuditoriaIndexRoute =
  AdminAdminAuditoriaIndexRouteImport.update({
    id: '/admin/auditoria/',
    path: '/admin/auditoria/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAdministradoresIndexRoute =
  AdminAdminAdministradoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminAdminAdministradoresRoute,
  } as any)
const AdminAdminUsuariosNovoRoute = AdminAdminUsuariosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminAdminUsuariosRoute,
} as any)
const AdminAdminUsuariosIdRoute = AdminAdminUsuariosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminUsuariosRoute,
} as any)
const AdminAdminCursosNovoRoute = AdminAdminCursosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminAdminCursosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/contato': typeof PublicContatoRoute
  '/sobre': typeof PublicSobreRoute
  '/admin/administradores': typeof AdminAdminAdministradoresRouteWithChildren
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/cursos': typeof AdminAdminCursosRouteWithChildren
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/mensagens': typeof AdminAdminMensagensRoute
  '/admin/noticias': typeof AdminAdminNoticiasRouteWithChildren
  '/admin/salas': typeof AdminAdminSalasRouteWithChildren
  '/admin/usuarios': typeof AdminAdminUsuariosRouteWithChildren
  '/cursos/$id': typeof PublicCursosIdRoute
  '/noticias/$id': typeof PublicNoticiasIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/cursos/': typeof PublicCursosIndexRoute
  '/noticias/': typeof PublicNoticiasIndexRoute
  '/admin/cursos/novo': typeof AdminAdminCursosNovoRoute
  '/admin/usuarios/$id': typeof AdminAdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminAdminUsuariosNovoRoute
  '/admin/administradores/': typeof AdminAdminAdministradoresIndexRoute
  '/admin/auditoria/': typeof AdminAdminAuditoriaIndexRoute
  '/admin/cotacoes/': typeof AdminAdminCotacoesIndexRoute
  '/admin/cursos/': typeof AdminAdminCursosIndexRoute
  '/admin/noticias/': typeof AdminAdminNoticiasIndexRoute
  '/admin/salas/': typeof AdminAdminSalasIndexRoute
  '/admin/usuarios/': typeof AdminAdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/contato': typeof PublicContatoRoute
  '/sobre': typeof PublicSobreRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/mensagens': typeof AdminAdminMensagensRoute
  '/cursos/$id': typeof PublicCursosIdRoute
  '/noticias/$id': typeof PublicNoticiasIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/cursos': typeof PublicCursosIndexRoute
  '/noticias': typeof PublicNoticiasIndexRoute
  '/admin/cursos/novo': typeof AdminAdminCursosNovoRoute
  '/admin/usuarios/$id': typeof AdminAdminUsuariosIdRoute
  '/admin/usuarios/novo': typeof AdminAdminUsuariosNovoRoute
  '/admin/administradores': typeof AdminAdminAdministradoresIndexRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaIndexRoute
  '/admin/cotacoes': typeof AdminAdminCotacoesIndexRoute
  '/admin/cursos': typeof AdminAdminCursosIndexRoute
  '/admin/noticias': typeof AdminAdminNoticiasIndexRoute
  '/admin/salas': typeof AdminAdminSalasIndexRoute
  '/admin/usuarios': typeof AdminAdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/sobre': typeof PublicSobreRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/admin/administradores': typeof AdminAdminAdministradoresRouteWithChildren
  '/_admin/admin/banners': typeof AdminAdminBannersRoute
  '/_admin/admin/cursos': typeof AdminAdminCursosRouteWithChildren
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/mensagens': typeof AdminAdminMensagensRoute
  '/_admin/admin/noticias': typeof AdminAdminNoticiasRouteWithChildren
  '/_admin/admin/salas': typeof AdminAdminSalasRouteWithChildren
  '/_admin/admin/usuarios': typeof AdminAdminUsuariosRouteWithChildren
  '/_public/cursos/$id': typeof PublicCursosIdRoute
  '/_public/noticias/$id': typeof PublicNoticiasIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/cursos/': typeof PublicCursosIndexRoute
  '/_public/noticias/': typeof PublicNoticiasIndexRoute
  '/_admin/admin/cursos/novo': typeof AdminAdminCursosNovoRoute
  '/_admin/admin/usuarios/$id': typeof AdminAdminUsuariosIdRoute
  '/_admin/admin/usuarios/novo': typeof AdminAdminUsuariosNovoRoute
  '/_admin/admin/administradores/': typeof AdminAdminAdministradoresIndexRoute
  '/_admin/admin/auditoria/': typeof AdminAdminAuditoriaIndexRoute
  '/_admin/admin/cotacoes/': typeof AdminAdminCotacoesIndexRoute
  '/_admin/admin/cursos/': typeof AdminAdminCursosIndexRoute
  '/_admin/admin/noticias/': typeof AdminAdminNoticiasIndexRoute
  '/_admin/admin/salas/': typeof AdminAdminSalasIndexRoute
  '/_admin/admin/usuarios/': typeof AdminAdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contato'
    | '/sobre'
    | '/admin/administradores'
    | '/admin/banners'
    | '/admin/cursos'
    | '/admin/dashboard'
    | '/admin/mensagens'
    | '/admin/noticias'
    | '/admin/salas'
    | '/admin/usuarios'
    | '/cursos/$id'
    | '/noticias/$id'
    | '/admin/'
    | '/cursos/'
    | '/noticias/'
    | '/admin/cursos/novo'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/admin/administradores/'
    | '/admin/auditoria/'
    | '/admin/cotacoes/'
    | '/admin/cursos/'
    | '/admin/noticias/'
    | '/admin/salas/'
    | '/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contato'
    | '/sobre'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/mensagens'
    | '/cursos/$id'
    | '/noticias/$id'
    | '/admin'
    | '/cursos'
    | '/noticias'
    | '/admin/cursos/novo'
    | '/admin/usuarios/$id'
    | '/admin/usuarios/novo'
    | '/admin/administradores'
    | '/admin/auditoria'
    | '/admin/cotacoes'
    | '/admin/cursos'
    | '/admin/noticias'
    | '/admin/salas'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/login'
    | '/_public/contato'
    | '/_public/sobre'
    | '/_public/'
    | '/_admin/admin/administradores'
    | '/_admin/admin/banners'
    | '/_admin/admin/cursos'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/mensagens'
    | '/_admin/admin/noticias'
    | '/_admin/admin/salas'
    | '/_admin/admin/usuarios'
    | '/_public/cursos/$id'
    | '/_public/noticias/$id'
    | '/_admin/admin/'
    | '/_public/cursos/'
    | '/_public/noticias/'
    | '/_admin/admin/cursos/novo'
    | '/_admin/admin/usuarios/$id'
    | '/_admin/admin/usuarios/novo'
    | '/_admin/admin/administradores/'
    | '/_admin/admin/auditoria/'
    | '/_admin/admin/cotacoes/'
    | '/_admin/admin/cursos/'
    | '/_admin/admin/noticias/'
    | '/_admin/admin/salas/'
    | '/_admin/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sobre': {
      id: '/_public/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof PublicSobreRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/noticias/': {
      id: '/_public/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof PublicNoticiasIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cursos/': {
      id: '/_public/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof PublicCursosIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/noticias/$id': {
      id: '/_public/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/noticias/$id'
      preLoaderRoute: typeof PublicNoticiasIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cursos/$id': {
      id: '/_public/cursos/$id'
      path: '/cursos/$id'
      fullPath: '/cursos/$id'
      preLoaderRoute: typeof PublicCursosIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/usuarios': {
      id: '/_admin/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminAdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/salas': {
      id: '/_admin/admin/salas'
      path: '/admin/salas'
      fullPath: '/admin/salas'
      preLoaderRoute: typeof AdminAdminSalasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/noticias': {
      id: '/_admin/admin/noticias'
      path: '/admin/noticias'
      fullPath: '/admin/noticias'
      preLoaderRoute: typeof AdminAdminNoticiasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/mensagens': {
      id: '/_admin/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminAdminMensagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cursos': {
      id: '/_admin/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminAdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/banners': {
      id: '/_admin/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminAdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/administradores': {
      id: '/_admin/admin/administradores'
      path: '/admin/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdminAdministradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/usuarios/': {
      id: '/_admin/admin/usuarios/'
      path: '/'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminAdminUsuariosIndexRouteImport
      parentRoute: typeof AdminAdminUsuariosRoute
    }
    '/_admin/admin/salas/': {
      id: '/_admin/admin/salas/'
      path: '/'
      fullPath: '/admin/salas/'
      preLoaderRoute: typeof AdminAdminSalasIndexRouteImport
      parentRoute: typeof AdminAdminSalasRoute
    }
    '/_admin/admin/noticias/': {
      id: '/_admin/admin/noticias/'
      path: '/'
      fullPath: '/admin/noticias/'
      preLoaderRoute: typeof AdminAdminNoticiasIndexRouteImport
      parentRoute: typeof AdminAdminNoticiasRoute
    }
    '/_admin/admin/cursos/': {
      id: '/_admin/admin/cursos/'
      path: '/'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AdminAdminCursosIndexRouteImport
      parentRoute: typeof AdminAdminCursosRoute
    }
    '/_admin/admin/cotacoes/': {
      id: '/_admin/admin/cotacoes/'
      path: '/admin/cotacoes'
      fullPath: '/admin/cotacoes/'
      preLoaderRoute: typeof AdminAdminCotacoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/auditoria/': {
      id: '/_admin/admin/auditoria/'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria/'
      preLoaderRoute: typeof AdminAdminAuditoriaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/administradores/': {
      id: '/_admin/admin/administradores/'
      path: '/'
      fullPath: '/admin/administradores/'
      preLoaderRoute: typeof AdminAdminAdministradoresIndexRouteImport
      parentRoute: typeof AdminAdminAdministradoresRoute
    }
    '/_admin/admin/usuarios/novo': {
      id: '/_admin/admin/usuarios/novo'
      path: '/novo'
      fullPath: '/admin/usuarios/novo'
      preLoaderRoute: typeof AdminAdminUsuariosNovoRouteImport
      parentRoute: typeof AdminAdminUsuariosRoute
    }
    '/_admin/admin/usuarios/$id': {
      id: '/_admin/admin/usuarios/$id'
      path: '/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminAdminUsuariosIdRouteImport
      parentRoute: typeof AdminAdminUsuariosRoute
    }
    '/_admin/admin/cursos/novo': {
      id: '/_admin/admin/cursos/novo'
      path: '/novo'
      fullPath: '/admin/cursos/novo'
      preLoaderRoute: typeof AdminAdminCursosNovoRouteImport
      parentRoute: typeof AdminAdminCursosRoute
    }
  }
}

interface AdminAdminAdministradoresRouteChildren {
  AdminAdminAdministradoresIndexRoute: typeof AdminAdminAdministradoresIndexRoute
}

const AdminAdminAdministradoresRouteChildren: AdminAdminAdministradoresRouteChildren =
  {
    AdminAdminAdministradoresIndexRoute: AdminAdminAdministradoresIndexRoute,
  }

const AdminAdminAdministradoresRouteWithChildren =
  AdminAdminAdministradoresRoute._addFileChildren(
    AdminAdminAdministradoresRouteChildren,
  )

interface AdminAdminCursosRouteChildren {
  AdminAdminCursosNovoRoute: typeof AdminAdminCursosNovoRoute
  AdminAdminCursosIndexRoute: typeof AdminAdminCursosIndexRoute
}

const AdminAdminCursosRouteChildren: AdminAdminCursosRouteChildren = {
  AdminAdminCursosNovoRoute: AdminAdminCursosNovoRoute,
  AdminAdminCursosIndexRoute: AdminAdminCursosIndexRoute,
}

const AdminAdminCursosRouteWithChildren =
  AdminAdminCursosRoute._addFileChildren(AdminAdminCursosRouteChildren)

interface AdminAdminNoticiasRouteChildren {
  AdminAdminNoticiasIndexRoute: typeof AdminAdminNoticiasIndexRoute
}

const AdminAdminNoticiasRouteChildren: AdminAdminNoticiasRouteChildren = {
  AdminAdminNoticiasIndexRoute: AdminAdminNoticiasIndexRoute,
}

const AdminAdminNoticiasRouteWithChildren =
  AdminAdminNoticiasRoute._addFileChildren(AdminAdminNoticiasRouteChildren)

interface AdminAdminSalasRouteChildren {
  AdminAdminSalasIndexRoute: typeof AdminAdminSalasIndexRoute
}

const AdminAdminSalasRouteChildren: AdminAdminSalasRouteChildren = {
  AdminAdminSalasIndexRoute: AdminAdminSalasIndexRoute,
}

const AdminAdminSalasRouteWithChildren = AdminAdminSalasRoute._addFileChildren(
  AdminAdminSalasRouteChildren,
)

interface AdminAdminUsuariosRouteChildren {
  AdminAdminUsuariosIdRoute: typeof AdminAdminUsuariosIdRoute
  AdminAdminUsuariosNovoRoute: typeof AdminAdminUsuariosNovoRoute
  AdminAdminUsuariosIndexRoute: typeof AdminAdminUsuariosIndexRoute
}

const AdminAdminUsuariosRouteChildren: AdminAdminUsuariosRouteChildren = {
  AdminAdminUsuariosIdRoute: AdminAdminUsuariosIdRoute,
  AdminAdminUsuariosNovoRoute: AdminAdminUsuariosNovoRoute,
  AdminAdminUsuariosIndexRoute: AdminAdminUsuariosIndexRoute,
}

const AdminAdminUsuariosRouteWithChildren =
  AdminAdminUsuariosRoute._addFileChildren(AdminAdminUsuariosRouteChildren)

interface AdminRouteChildren {
  AdminAdminAdministradoresRoute: typeof AdminAdminAdministradoresRouteWithChildren
  AdminAdminBannersRoute: typeof AdminAdminBannersRoute
  AdminAdminCursosRoute: typeof AdminAdminCursosRouteWithChildren
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminMensagensRoute: typeof AdminAdminMensagensRoute
  AdminAdminNoticiasRoute: typeof AdminAdminNoticiasRouteWithChildren
  AdminAdminSalasRoute: typeof AdminAdminSalasRouteWithChildren
  AdminAdminUsuariosRoute: typeof AdminAdminUsuariosRouteWithChildren
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminAuditoriaIndexRoute: typeof AdminAdminAuditoriaIndexRoute
  AdminAdminCotacoesIndexRoute: typeof AdminAdminCotacoesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAdministradoresRoute: AdminAdminAdministradoresRouteWithChildren,
  AdminAdminBannersRoute: AdminAdminBannersRoute,
  AdminAdminCursosRoute: AdminAdminCursosRouteWithChildren,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminMensagensRoute: AdminAdminMensagensRoute,
  AdminAdminNoticiasRoute: AdminAdminNoticiasRouteWithChildren,
  AdminAdminSalasRoute: AdminAdminSalasRouteWithChildren,
  AdminAdminUsuariosRoute: AdminAdminUsuariosRouteWithChildren,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminAuditoriaIndexRoute: AdminAdminAuditoriaIndexRoute,
  AdminAdminCotacoesIndexRoute: AdminAdminCotacoesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicContatoRoute: typeof PublicContatoRoute
  PublicSobreRoute: typeof PublicSobreRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCursosIdRoute: typeof PublicCursosIdRoute
  PublicNoticiasIdRoute: typeof PublicNoticiasIdRoute
  PublicCursosIndexRoute: typeof PublicCursosIndexRoute
  PublicNoticiasIndexRoute: typeof PublicNoticiasIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContatoRoute: PublicContatoRoute,
  PublicSobreRoute: PublicSobreRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCursosIdRoute: PublicCursosIdRoute,
  PublicNoticiasIdRoute: PublicNoticiasIdRoute,
  PublicCursosIndexRoute: PublicCursosIndexRoute,
  PublicNoticiasIndexRoute: PublicNoticiasIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
